wmbahari:
  name: "warung makan bahari app"
  api:
    url: "localhost:3000"
    token: "123"
  postgres:
    host: "localhost"
    port: "5432"
    user: "golang"
    password: "holden"
    name: "wm_bahari"